# .github/workflows/deploy.yml

name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # Add this block
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # This is the folder containing your static HTML, CSS, JS
